### PR TITLE
Bump pandoc version

### PR DESCRIPTION
**Pull request by HeikoTheissen**
To Do
- [x] pandoc test output differs
- [x] puppeteer output differs
- [x] puppeteer test "hangs"

### CODE REVIEW

**Review by ralfhandl — APPROVED** [review]

**Review by ralfhandl — CHANGES_REQUESTED** [review]
`npm test` fails two test cases
- pandoc test output differs
- puppeteer output differs, test "hangs" and doesn't exit

**Review by ralfhandl — CHANGES_REQUESTED** [review]
Puppeteer test still fails with

~~~
       Puppeteer:

      AssertionError [ERR_ASSERTION]: 10.350000381469727 == 10
      + expected - actual

      -10.350000381469727
      +10

      at Context.<anonymous> (test\build.test.js:54:12)
~~~

**Comment by HeikoTheissen** [comment]
Changed browser behavior after puppeteer upgrade

**Review by ralfhandl — APPROVED** [review]
Feel free to merge

**Pull request merged**
